openapi: 3.0.1
info:
  title: Java eval API
  description: Manage API with multiple environment
  version: "1.0"
servers:
  - url: https://$(catalog.host)/java-eval-api

tags:
  - name: InfoController

paths:
  /java-eval-api/ping:
    get:
      operationId: ping
      summary: Ping api
      description: Should answer when the path is ready
      tags:
        - InfoController
      responses:
        204:
          description: Ping
          content: { }
  /java-eval-api/mirror-outgoing-header:
    get:
      operationId: mirrorOutgoingHeaders
      summary: Call a HTTP mirror endpoint, to inspect the outgoing header
      tags:
        - MirrorController
      responses:
        200:
          description: Outgoing headers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Header'
        400:
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
    Header:
      type: object
      properties:
        name:
          type: string
        value:
          type: string